# mymodbus.conf
web_server.bind_address=<bind IP address>
web_server.bind_port=8080
modbus.serial_port=/dev/ttyACM0
general.log_path=/home/petste/MyModbus/logs/app.log
general.log_level=Warn
general.log_to_stdout=false